

# This file was *autogenerated* from the file aggr_attacks_ternary.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0p1667 = RealNumber('0.1667'); _sage_const_3329 = Integer(3329); _sage_const_0p1666 = RealNumber('0.1666'); _sage_const_160 = Integer(160); _sage_const_0p16666666666666666 = RealNumber('0.16666666666666666'); _sage_const_170 = Integer(170); _sage_const_180 = Integer(180); _sage_const_190 = Integer(190); _sage_const_200 = Integer(200); _sage_const_210 = Integer(210); _sage_const_5 = Integer(5); _sage_const_50 = Integer(50); _sage_const_56 = Integer(56); _sage_const_6 = Integer(6); _sage_const_64 = Integer(64); _sage_const_74 = Integer(74); _sage_const_83 = Integer(83); _sage_const_90 = Integer(90); _sage_const_60 = Integer(60); _sage_const_65 = Integer(65); _sage_const_201 = Integer(201); _sage_const_10 = Integer(10); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_12 = Integer(12); _sage_const_4 = Integer(4); _sage_const_2 = Integer(2); _sage_const_0p = RealNumber('0.'); _sage_const_10p = RealNumber('10.'); _sage_const_100 = Integer(100); _sage_const_1p = RealNumber('1.'); _sage_const_100p = RealNumber('100.'); _sage_const_179854p06032 = RealNumber('179854.06032')
import os, re
import time

import pickle 
import numpy as np
from hybrid_estimator.batchCVP import batchCVPP_cost
from sample import Distribution, ternaryDist, centeredBinomial

from hybrid_estimator.batchCVP import batchCVPP_cost
out_path = "lwe_instances/reduced_lattices/"


sec_type = "ternary"
sec_param = _sage_const_0p1667 
print(f"sec_param:{sec_param}")
q = _sage_const_3329 
dist=sec_type
dist_param=_sage_const_0p1666 

with open("./lwe_instances/reduced_lattices/exp_[160, 170, 180, 190, 200]_3329_ternary_0.1667.pkl", "rb") as file:
    out = pickle.load( file )
    
lwe_inst = [ #do we need lats_per_dim and inst_per_lat?
    {"n": _sage_const_160 , "q": _sage_const_3329 , "dist": 'ternary', "dist_param": _sage_const_0p16666666666666666 },
    {"n": _sage_const_170 , "q": _sage_const_3329 , "dist": 'ternary', "dist_param": _sage_const_0p16666666666666666 },
    {"n": _sage_const_180 , "q": _sage_const_3329 , "dist": 'ternary', "dist_param": _sage_const_0p16666666666666666 },
    {"n": _sage_const_190 , "q": _sage_const_3329 , "dist": 'ternary', "dist_param": _sage_const_0p16666666666666666 },
    {"n": _sage_const_200 , "q": _sage_const_3329 , "dist": 'ternary', "dist_param": _sage_const_0p16666666666666666 },
    {"n": _sage_const_210 , "q": _sage_const_3329 , "dist": 'ternary', "dist_param": _sage_const_0p16666666666666666 },
]

hparams = { #n_guess_coord's, n_slicer_coord from preprocessing.py
    _sage_const_160 : (_sage_const_5 ,_sage_const_50 ),
    _sage_const_170 : (_sage_const_5 ,_sage_const_56 ),
    _sage_const_180 : (_sage_const_6 ,_sage_const_64 ),
    _sage_const_190 : (_sage_const_6 ,_sage_const_74 ),
    _sage_const_200 : (_sage_const_6 ,_sage_const_83 ),
    _sage_const_210 : (_sage_const_6 ,_sage_const_90 )
}

outpre = []
corresponding_blocksizes = {_sage_const_160 :_sage_const_50 , _sage_const_170 :_sage_const_50 , _sage_const_180 :_sage_const_60 , _sage_const_190 : _sage_const_60 , _sage_const_200 : _sage_const_65 }
for n in range(_sage_const_160 ,_sage_const_201 ,_sage_const_10 ):
    betapre = corresponding_blocksizes[n]
    for seed in range(_sage_const_10 ):
        filename = f"report_pre_{n}_{q}_{sec_type}_{sec_param:0.4f}_{seed}_{betapre}.pkl"
        with open( out_path + filename, "rb" ) as file:
            outpre.append( pickle.load( file ) )

maxbeta = _sage_const_0 
for oo in out:
    if oo["beta"] > maxbeta:
        maxbeta = oo["beta"]

l = {}
ddl = {}

#extracting the mean blocksize
for oo in out:
    if not oo["kyb"][_sage_const_0 ] in l.keys():
        l[oo["kyb"][_sage_const_0 ]] = [ oo["beta"], _sage_const_1  ]
        ddl[oo["kyb"][_sage_const_0 ]] = [ oo["beta"] ]
    else:
        l[oo["kyb"][_sage_const_0 ]][_sage_const_0 ] += oo["beta"]
        l[oo["kyb"][_sage_const_0 ]][_sage_const_1 ] += _sage_const_1 
        ddl[oo["kyb"][_sage_const_0 ]].append( oo["beta"] )

for key in l.keys():
    l[key] = l[key][_sage_const_0 ]/l[key][_sage_const_1 ].n()
    ddl[key] = np.std(ddl[key])

l_primal = l

P = list_plot(l, plotjoined=True, marker='.',color="red", legend_label="Experiment")

filename = f"betaprimal_d_{sec_type}_{sec_param:0.4f}.png"
P.save_image( filename, axes_labels=['$n$', '$\\beta$'], title=f'$\\beta$ sufficient to solve uSVP, Kyber-$n$. 5 tours progressive BKZ. 100 experiments.', figsize=_sage_const_12  )
print(f"Saved figure to {filename}")


if sec_type=="binomial":
    distrib = centeredBinomial(sec_param)
elif sec_type=="ternary":
     distrib = ternaryDist(sec_param)

# extracting the primal preprocessing timing
r = {}
for oo in outpre:
    n, seed = oo['kyb'][_sage_const_0 ], oo['kyb'][_sage_const_4 ][_sage_const_0 ]
    if not n in r.keys(): 
        r[n] = [ oo["time"], _sage_const_1  ]
    else:
        r[n][_sage_const_0 ] += oo["time"]
        r[n][_sage_const_1 ] += _sage_const_1 


#averaging the timing
for key in r.keys():
    r[key] = r[key][_sage_const_0 ]/r[key][_sage_const_1 ].n()

# extracting the primal attack timing
l = {}
for oo in out:
    if not oo["kyb"][_sage_const_0 ] in l.keys():
        l[oo["kyb"][_sage_const_0 ]] = [ oo["time"], _sage_const_1  ]
    else:
        l[oo["kyb"][_sage_const_0 ]][_sage_const_0 ] += oo["time"]
        l[oo["kyb"][_sage_const_0 ]][_sage_const_1 ] += _sage_const_1 

# averaging it
for key in l.keys():
    l[key] = l[key][_sage_const_0 ]/l[key][_sage_const_1 ].n() + r[key]
    ddl[key] = np.std(ddl[key])

primal_timings = deepcopy(l)
# - - - 
P = list_plot_semilogy(l, plotjoined=True, legend_label="Primal attack")

data = []
path = "./lwe_instances/reduced_lattices/"
pattern = re.compile(r'''
    ^report_prehyb_             
    (?P<n>\d+)_                 
    (?P<q>\d+)_                 
    (?P<dist>[^_]+)_            
    (?P<dist_param>[+-]?\d+\.\d{4})_  
    (?P<seed>\d+)_              
    (?P<kappa>\d+)_             
    (?P<sieve_dim_min>\d+)_     
    (?P<sieve_dim_max>\d+)_     
    (?P<beta_bkz>\d+)           
    \.pkl$
''', re.VERBOSE)
regex = re.compile(pattern)

for path, directories, files in os.walk(path):
    for candidate in files:
        match = regex.match(candidate)
        if match and sec_type in candidate and f"{sec_param:0.4f}" in candidate:
            gd = match.groupdict()
            n             = int(gd['n'])
            q             = int(gd['q'])
            dist          = gd['dist']
            dist_param    = float(gd['dist_param'])
            seed          = int(gd['seed'])
            kappa         = int(gd['kappa'])
            sieve_dim_min = int(gd['sieve_dim_min'])
            sieve_dim_max = int(gd['sieve_dim_max'])
            beta_bkz      = int(gd['beta_bkz'])
            try:
                try:
                    if ( 
                        n in [tmp["n"] for tmp in lwe_inst] and
                        kappa == hparams[n][_sage_const_0 ] and
                        beta_bkz == hparams[n][_sage_const_1 ] and
                        sec_type in candidate and
                        f"{sec_param:0.4f}" in candidate and
                        f"_{hparams[n][_sage_const_0 ]}_" in candidate
                    ):
                        with open( path+candidate, "rb" ) as file:
                            data.append( pickle.load(file) )
                except KeyError as err:
                    print( err )
                    pass
            except ValueError as expt:
                print(expt)
                pass

processed_data = {}
for D in data: #loading from the text output
    n, q, dist, dist_param, seed = D["params"]
    if dist != sec_type:
        print(f"wrong dist: {dist}")
        continue
    sieve_dim_max = D["sieve_dim_max"]
    sieve_dim_min = D["sieve_dim_min"]
    kappa = D["kappa"]
    if kappa != hparams[n][_sage_const_0 ]: #or sieve_dim_min != hparams[n][1]:
        continue
    
    bkz_runtime = D["bkz_runtime"]
    bdgl_runtime = D["bdgl_runtime"]

    nsampl = ceil( _sage_const_2  ** ( distrib.entropy * kappa ) )

    for i in range(len(bdgl_runtime)):
        sievedim = sieve_dim_max-i
        latdim = n - kappa
        if not (n,kappa,sievedim,latdim) in processed_data.keys():
            processed_data[(n,kappa,sievedim,latdim)] = {"bkz_runtime": [], "bdgl_runtime": [], "succrate": _sage_const_0p }
        processed_data[(n,kappa,sievedim,latdim)]["bkz_runtime"].append( bkz_runtime )
        processed_data[(n,kappa,sievedim,latdim)]["bdgl_runtime"].append( bdgl_runtime )

aggrigated_data = {}
for (n,k,sievedim,latdim) in processed_data.keys():
    D = processed_data[(n,k,sievedim,latdim)]
    bkz_runtime = np.mean( D["bkz_runtime"] )
    bdgl_runtime = np.mean( D["bdgl_runtime"], axis=int(_sage_const_0 ) )
    
    aggrigated_data[ (n,k,sievedim) ] =  bkz_runtime + np.zeros(len(bdgl_runtime))

l0, l1 = {}, {}

for (n,k,sievedim) in aggrigated_data.keys():
    l0[n] = aggrigated_data[(n,k,sievedim)][-_sage_const_1 ]
    l1[n] = aggrigated_data[(n,k,sievedim)][_sage_const_0 ]

preprocess_hyb_time = deepcopy(l0)

P += list_plot_semilogy(l0, plotjoined=True, base=_sage_const_10 , axes_labels=["$n$", "$log(T)$"], color="green", legend_label="Hybrid preprocessing")

# - - - processing the hybrid attack
L = {}
available_ns = []

data = []
path = "./lwe_instances/reduced_lattices/"
pattern = re.compile(r'''
    ^tph_                          
    (?P<n>\d+)_                    
    (?P<dist>[^_]+)_               
    (?P<dist_param>[+-]?\d+\.\d{4})_  
    (?P<kappa>\d+)_                
    (?P<beta_bkz>\d+)_             
    (?P<sieve_dim_max>\d+)         
    \.pkl$                         
''', re.VERBOSE)
regex = re.compile(pattern)

lol=_sage_const_0 
max_n = _sage_const_0 
available_ns = []
for path, directories, files in os.walk(path):
    lol+=_sage_const_1 
    for candidate in files:
        match = regex.match(candidate)
        if match and sec_type in candidate and f"{sec_param:0.4f}" in candidate:
            gd = match.groupdict()
            n             = int(gd['n'])
            # dist          = gd['dist']
            # dist_param    = float(gd['dist_param'])
            # kappa         = int(gd['kappa'])
            # sieve_dim_max = int(gd['sieve_dim_max'])
            # beta_bkz      = int(gd['beta_bkz'])
            # print(True)
            if not n in available_ns:
                available_ns.append(n)
            with open(path+candidate,"rb") as file:
                L.update( pickle.load(file) )
            
wtimes = {}
succs = {}
for n in available_ns:
    wtimes[n] = []
    if not n in succs:
        succs[n] = [_sage_const_0 ,_sage_const_0 ]
    
NRAND_FACTOR = _sage_const_10p 
for key in L:
    n, _, n_slicer_coord, n_guess_coord, _ = key
    if n_guess_coord == hparams[n][_sage_const_0 ]:
        nrand_, _ = batchCVPP_cost(n_slicer_coord,_sage_const_100 ,L[key]["g6k_len"] **(_sage_const_1p /n_slicer_coord),_sage_const_1 )
        nrand = ceil(NRAND_FACTOR*(_sage_const_1p /nrand_)**n_slicer_coord)
        utar_per_batch = ceil( L[key]["g6k_len"] / nrand ) #how many unique targets in batch
    
        curtime = ( abs( L[key]["wrong_guess_time_alg2"] ) + abs( L[key]["wrong_guess_time_alg3"] ) )
        overhead_tsieve = L[key]["overhead_tsieve"]
        batnum = ceil( L[key]["key_num"]/utar_per_batch )
        curtime *= batnum  #time * how many batches needed
        wtimes[n].append( [curtime , overhead_tsieve] )
        succs[n][_sage_const_0 ]+=_sage_const_1 
        succs[n][_sage_const_1 ]+=L[key]['succ']
print(f"- - - ")

for n in available_ns:
    wtimes[n] = np.mean(wtimes[n], axis=_sage_const_0 ) #we don`t need to sieve for each new batch
    try:
        cur_succ_rate = float(succs[n][_sage_const_1 ] / succs[n][_sage_const_0 ])
    except TypeError:
        cur_succ_rate = _sage_const_1 
    succs[n] = cur_succ_rate if cur_succ_rate>_sage_const_0  else _sage_const_1 /_sage_const_100p 

ltot_hyb_att = {}

for key in wtimes.keys():
    walltime = wtimes[key]
    ltot_hyb_att[key] = float( l1[key] + walltime[_sage_const_1 ] + ( _sage_const_2 *walltime[_sage_const_0 ] ) / succs[key] )  #success rate is 1/2 * slicer's proba


P += list_plot_semilogy(ltot_hyb_att, plotjoined=True, base=_sage_const_10 , axes_labels=["$n$", "$log(T)$"], color="red", legend_label="Hybrid total")
plotfilename = f"time_{dist}_{sec_param:0.4f}_{available_ns}.png"
# - - - now we process the two-step attack

data = []
path = "./lwe_instances/reduced_lattices/"
pattern = re.compile(r'''
    ^tsa_                          
    (?P<n>\d+)_                    
    (?P<dist>[^_]+)_               
    (?P<dist_param>[+-]?\d+\.\d{4})     
    \.pkl$                         
''', re.VERBOSE)
regex = re.compile(pattern)

L_two_step = {}
for path, directories, files in os.walk(path):
    for candidate in files:
        match = regex.match(candidate)
        if match and sec_type in candidate and f"{sec_param:0.4f}" in candidate:
            gd = match.groupdict()
            n             = int(gd['n'])
            # dist          = gd['dist']
            # dist_param    = float(gd['dist_param'])
            
            available_ns.append(n)
            with open(path+candidate,"rb") as file:
                L_two_step[n] = pickle.load(file)

L_two_step_ = {}
for n in L_two_step.keys():
    Ts = []

    succs = [_sage_const_0 ,_sage_const_0 ]
    cntr=_sage_const_0 
    data = L_two_step[n]
    for D in data:
        tmp = _sage_const_0 
        for bkz in D["bkz_invoked"].values():
            tmp +=  sum( bkz["times"] )
        lol = sum( [ll[_sage_const_1 ] for ll in D["svp_calls"]] )
        tmp += sum( [ll[_sage_const_1 ] for ll in D["svp_calls"]] )
        Ts.append( tmp )
        succs[_sage_const_1 ]+=_sage_const_1 
        cntr+=_sage_const_1 
        if D["succ"]:
            succs[_sage_const_0 ]+=_sage_const_1 

    avgtime = np.mean( Ts )
    print( avgtime, avgtime*succs[_sage_const_1 ]/succs[_sage_const_0 ] )
    print( succs )
    L_two_step_[n] = avgtime*succs[_sage_const_1 ]/succs[_sage_const_0 ]

L_two_step_[_sage_const_210 ] = _sage_const_179854p06032 

P += list_plot_semilogy(L_two_step_, plotjoined=True, base=_sage_const_10 , axes_labels=["$n$", "$log(T)$"], color="orange", legend_label="Two-step total")

print(f"succs: {succs}")
print(f"hyb_preproc: {l0}")
print(f"ltot_hyb_att: {ltot_hyb_att}")
print(f"primal_timings: {primal_timings}")
print(f"two_step_timings: {L_two_step_}")
# - - -
filename = f"hybVSprima_d_{dist}_{sec_param:0.4f}.png"
P.save_image( filename, title=f'Preprocessing + attack Time for Hybrid, Kyber-$n$. Ternary {sec_param}', figsize=_sage_const_12  )
print(f"Saved figure to {filename}")


