import numpy as np
global BKZ_MAX_LOOPS
global BKZ_SIEVING_CROSSOVER
global N_SIEVE_THREADS
global DTYPE
global N_MAX_SLICER_ITERATIONS
global NRAND_FACTOR
global EPS2
global NPROJ_TESTS
global SATURATION_SCALAR

BKZ_MAX_LOOPS = 2
BKZ_SIEVING_CROSSOVER = 55
N_SIEVE_THREADS = 5
N_MAX_SLICER_ITERATIONS = 400
NRAND_FACTOR = 5.
DTYPE = np.float64 #np.longdouble or np.float64
EPS2 = 1.0001 #(1+epsilon) squared
NPROJ_TESTS = 2048
SATURATION_SCALAR = 1.05