name: Tests

on: 
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # weekly

env:
  JOBS: 2
  DEPS: libgmp-dev libmpfr-dev libqd-dev libtool autoconf python3-pip python3-dev python3-flake8
  
jobs:
  python3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check out
        uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install $DEPS
      - name: Dependencies
        run: |
          git clone https://github.com/fplll/fplll
          cd fplll || exit
          ./autogen.sh
          ./configure --disable-static --prefix=/usr --with-max-enum-dim=64 --with-max-parallel-enum-dim=20
          make -j $JOBS
          sudo make install
          cd ..

          git clone https://github.com/fplll/fpylll
          cd fpylll || exit
          pip install -r requirements.txt
          pip install -r suggestions.txt
          python setup.py build_ext -j $JOBS
          python setup.py install
          cd ..

          # Otherwise py.test may fail
          rm -rf ./fplll
          rm -rf ./fpylll

          # G6K requirements
          pip install -r requirements.txt
          
      - name: Compile Kernel
        run: |
          autoreconf -i
          CXXFLAGS="-Werror" ./configure
          make -j $JOBS

      - name: Compile Python
        run: python setup.py build_ext -j $JOBS --inplace

      - name: Test
        run: python -m pytest
